set colorcolumn=81
set number
set wildmenu
set ignorecase
set scrolloff=5
set title
syntax on

" INDENTATION
set autoindent
"   ts        sw           sts  
set tabstop=4 shiftwidth=4 softtabstop=4 expandtab
" overrides
autocmd FileType elm :setlocal sw=2 ts=2 sts=2
